@BaseUrl = http://localhost:5098


POST {BaeUrl}/api/auth/organization/register/

{
  "name": "comp1",
  "firstName": "com",
  "lastName": "coom",
  "tenantCode": "comp1",
  "email": "comp1@gmail.com",
  "password": "comp1234"
}

###
